environment:
  global:
    RUST_BACKTRACE: 1
    Features: "use-mock-crust"
  matrix:
    - RUST_VERSION: stable
branches:
  only:
    - master
    - 0.23
clone_depth: 50

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
        Start-FileDownload "$url/Install%20Rustup.ps1" -FileName "Install Rustup.ps1"
        Start-FileDownload "$url/Build.ps1" -FileName "Build.ps1"
        Start-FileDownload "$url/Run%20Tests.ps1" -FileName "Run Tests.ps1"
        . ".\Install Rustup.ps1"

platform:
  - x86
  - x64

configuration:
#  - Debug
  - Release

build_script:
  - ps: . ".\Build.ps1"

test_script:
  - ps: . ".\Run Tests.ps1"
        # cd $env:APPVEYOR_BUILD_FOLDER
        # cargo run --release --example ci_test > output.log
        # type output.log
