environment:
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable
branches:
  only:
    - master
    - stable
clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor/Install%20Rustup.ps1"
        Invoke-WebRequest $url -OutFile "Install Rustup.ps1"
        . ".\Install Rustup.ps1"

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - cargo rustc --verbose --release -- --test -Zno-trans

test_script:
  - cargo test --verbose --release --features use-mock-crust
