[package]

name = "routing"
version = "0.1.3"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/routing/"
repository = "https://github.com/dirvine/routing"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"


[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide = "*"
rand = "*"
message_filter = "*"
lru_time_cache = "0.1.0"
crust = "0.0.4"
